------------------------------------------------------------
-- CRIAÇÃO DAS TABELAS BÁSICAS (cliente, conta, emprestimo)
------------------------------------------------------------

CREATE TABLE cliente (
    cod_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cidade VARCHAR2(100)
);

CREATE TABLE conta (
    conta_numero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_cliente NUMBER REFERENCES cliente(cod_cliente),
    saldo NUMBER(12,2) DEFAULT 0
);

CREATE TABLE emprestimo (
    emprestimo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cod_cliente NUMBER REFERENCES cliente(cod_cliente),
    valor NUMBER(12,2) NOT NULL
);

------------------------------------------------------------
-- INSERÇÃO DE DADOS DE EXEMPLO
------------------------------------------------------------

INSERT INTO cliente (nome, cidade) VALUES
('Ana Martins', 'São Paulo');
INSERT INTO cliente (nome, cidade) VALUES
('Bruno Lopes', 'Rio de Janeiro');
INSERT INTO cliente (nome, cidade) VALUES
('Carla Souza', 'Curitiba');
INSERT INTO cliente (nome, cidade) VALUES
('Diego Ramos', 'Belo Horizonte');

INSERT INTO conta (cod_cliente, saldo) VALUES (1, 2530.75);
INSERT INTO conta (cod_cliente, saldo) VALUES (2, 10000.00);
INSERT INTO conta (cod_cliente, saldo) VALUES (3, 50200.90);
INSERT INTO conta (cod_cliente, saldo) VALUES (4, 780.30);

INSERT INTO emprestimo (cod_cliente, valor) VALUES (1, 4000.00);
INSERT INTO emprestimo (cod_cliente, valor) VALUES (2, 8500.00);
INSERT INTO emprestimo (cod_cliente, valor) VALUES (3, 12000.50);
INSERT INTO emprestimo (cod_cliente, valor) VALUES (4, 3000.00);

------------------------------------------------------------
-- SEÇÃO 12 – CONVERSÕES
------------------------------------------------------------

-- 1️⃣ Exibir número da conta e saldo formatado
SELECT conta_numero,
       TO_CHAR(saldo, 'FM999G999G999D00') AS saldo_formatado
FROM conta;

-- 2️⃣ Data atual no formato DD/MM/YYYY
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS data_atual FROM DUAL;

-- 3️⃣ Nome + cidade
SELECT nome || ' - ' || cidade AS cliente_cidade FROM cliente;

-- 4️⃣ Empréstimos > 5000 formatados
SELECT emprestimo_id,
       TO_CHAR(valor, 'L999G999D00') AS valor_formatado
FROM emprestimo
WHERE valor > 5000;

------------------------------------------------------------
-- SEÇÃO 13 – TIPOS DE DADOS AVANÇADOS
------------------------------------------------------------

ALTER TABLE cliente
ADD data_cadastro TIMESTAMP DEFAULT SYSTIMESTAMP;

UPDATE cliente
SET data_cadastro = SYSTIMESTAMP - (cod_cliente * INTERVAL '10' DAY);

SELECT nome,
       TRUNC(SYSDATE - data_cadastro) AS dias_desde_cadastro
FROM cliente;

ALTER TABLE cliente
ADD tempo_fidelidade INTERVAL YEAR TO MONTH;

UPDATE cliente
SET tempo_fidelidade = INTERVAL '2-3' YEAR TO MONTH;

SELECT nome,
       data_cadastro,
       ADD_MONTHS(data_cadastro, 3) AS renovacao_prevista
FROM cliente;

------------------------------------------------------------
-- SEÇÃO 14 – CONSTRAINTS
------------------------------------------------------------

CREATE TABLE cartao_credito (
    cartao_numero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_cod NUMBER REFERENCES cliente(cod_cliente),
    limite_credito NUMBER(10,2) NOT NULL,
    status VARCHAR2(10) CHECK (status IN ('ATIVO', 'BLOQUEADO', 'CANCELADO'))
);

-- Teste: tentativa de valor nulo (vai gerar erro se executar)
-- INSERT INTO cartao_credito (cliente_cod, limite_credito, status)
-- VALUES (1, NULL, 'ATIVO');

INSERT INTO cartao_credito (cliente_cod, limite_credito, status)
VALUES (1, 4000, 'ATIVO');
INSERT INTO cartao_credito (cliente_cod, limite_credito, status)
VALUES (2, 2500, 'BLOQUEADO');
INSERT INTO cartao_credito (cliente_cod, limite_credito, status)
VALUES (3, 6000, 'ATIVO');

CREATE TABLE transacao (
    transacao_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cartao_numero NUMBER REFERENCES cartao_credito(cartao_numero),
    valor NUMBER(10,2) CHECK (valor > 0),
    data_transacao TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Teste: valor negativo (gera erro)
-- INSERT INTO transacao (cartao_numero, valor) VALUES (1, -150);

INSERT INTO transacao (cartao_numero, valor) VALUES (1, 250);
INSERT INTO transacao (cartao_numero, valor) VALUES (1, 180.5);
INSERT INTO transacao (cartao_numero, valor) VALUES (3, 1200);

SELECT c.nome, cc.limite_credito
FROM cliente c
JOIN cartao_credito cc ON c.cod_cliente = cc.cliente_cod
WHERE cc.status = 'ATIVO' AND cc.limite_credito > 3000;

CREATE OR REPLACE VIEW vw_clientes_com_cartao AS
SELECT c.nome, c.cidade, cc.status
FROM cliente c
JOIN cartao_credito cc ON c.cod_cliente = cc.cliente_cod;

SELECT * FROM vw_clientes_com_cartao;
